### ISSUE TITLE
Enhancement: sort contents of help

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property-manager#10]
if you type --help the output is not sorted. It would be much easier to find the right parameter if the list of commands would be sorted alphabetically. Instead of:

>   new-pipeline|np [options] [environments...]        Create a new pipeline with provided attributes. This will also create one property for each environment.
>   set-default|sd [options]                           Set the default pipeline and or the default section name from .edgerc
>   show-defaults|sf                                   Show default settings for this workspace
>   merge|m [options] <environment>                    Merge template json and variable values into a PM/PAPI ruletree JSON document, stored in dist folder in the current pipeline folder
>   search|s <name>                                    Search for properties by name
>   set-prefixes|sp <useprefix>                        Set or unset use of prefixes for current user credentials and setup
>   set-ruleformat|srf <ruleformat>                    Set ruleformat for current user credentials and setup
>   list-contracts|lc                                  List contracts available to current user credentials and setup
>   list-products|lp [options]                         List products available under provided contract ID and client ID available to current user credentials and setup
>   list-groups|lg                                     List groups available to current user credentials and setup
>   list-cpcodes|lcp [options]                         List cpcodes available to current user credentials and setup.
>   show-ruletree|sr [options] <environment>           Fetch latest version of property rule tree for provided environment
>   save|sv [options] <environment>                    Save rule tree and hostnames for provided environment. Edge hostnames are also created if needed.
>   list-edgehostnames|leh [options]                   List edge hostnames available to current user credentials and setup (this could be a long list).
>   list-status|lstat [options]                        Show status of pipeline
>   promote|pm [options] [targetEnvironment]           Promote (activate) an environment. This command also executes the merge and save commands mentioned above by default.
>   check-promotion-status|cs [options] <environment>  Check status of promotion (activation) of an environment.
>   help [cmd]                                         display help for [cmd]

we could indicate:

>   check-promotion-status|cs [options] <environment>  Check status of promotion (activation) of an environment.
>   help [cmd]                                         display help for [cmd]
>   list-contracts|lc                                  List contracts available to current user credentials and setup
>   list-cpcodes|lcp [options]                         List cpcodes available to current user credentials and setup.
>   list-edgehostnames|leh [options]                   List edge hostnames available to current user credentials and setup (this could be a long list).
>   list-groups|lg                                     List groups available to current user credentials and setup
>   list-products|lp [options]                         List products available under provided contract ID and client ID available to current user credentials and setup
>   list-status|lstat [options]                        Show status of pipeline
>   merge|m [options] <environment>                    Merge template json and variable values into a PM/PAPI ruletree JSON document, stored in dist folder in the current pipeline folder
>   new-pipeline|np [options] [environments...]        Create a new pipeline with provided attributes. This will also create one property for each environment.
>   promote|pm [options] [targetEnvironment]           Promote (activate) an environment. This command also executes the merge and save commands mentioned above by default.
>   save|sv [options] <environment>                    Save rule tree and hostnames for provided environment. Edge hostnames are also created if needed.
>   search|s <name>                                    Search for properties by name
>   set-default|sd [options]                           Set the default pipeline and or the default section name from .edgerc
>   set-prefixes|sp <useprefix>                        Set or unset use of prefixes for current user credentials and setup
>   set-ruleformat|srf <ruleformat>                    Set ruleformat for current user credentials and setup
>   show-defaults|sf                                   Show default settings for this workspace
>   show-ruletree|sr [options] <environment>           Fetch latest version of property rule tree for provided environment
>

**Comment by DidierFort** [comment]
I think we need categories along with the sort, examples:
- List and search functions,
- Environment setup,
...

**Comment by lkowalsk-akamai-com** [comment]
Help output is sorted properly now.
