### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli-property-manager#15]
Installation fails with the below message.
```
Unable to run package manager: exit status 1
```
There is no further message or logs to debug the cause.

**Comment by jnchin-james** [comment]
Thanks for bringing this to our attention.

I believe this is actually an error thrown from the Akamai CLI.  I would recommend posting a comment there (https://github.com/akamai/cli)

but my guess is that its not able to find NPM/Node.  Did you install NVM per the readme?  If you are using a mac, you could do "brew install nvm" and then do "nvm install v8.9.1"

**Comment by vreddhi** [comment]
@jnchin-james I have referenced the installation issue under CLI. Just to let you know, the above node/npm installation also didn't resolve.

**Comment by jnchin-james** [comment]
I see.

I would recommend installing NVM and using NVM to install npm.  Try to use the instructions on this site here:

http://nvm.sh/

Let me know if you are able to install nvm and then npm

**Comment by vreddhi** [comment]
[2018-10-16T07_55_50_047Z-debug.log](https://github.com/akamai/cli-property-manager/files/2549865/2018-10-16T07_55_50_047Z-debug.log)

Here are the logs when i try installation manually.

**Comment by vreddhi** [comment]
Thank you @jnchin-james . The issue was the registry was pointing to the wrong repository. Correcting that resolved the issue.

**Comment by tankchintan** [comment]
I am facing this issue as well @jnchin-james @vreddhi.

Here is the bash output,
```
➜  npm --version
7.15.1
➜  nvm use node
Now using node v16.3.0 (npm v7.15.1)
➜  akamai install property-manager
Attempting to fetch command from https://github.com/akamai/cli-property-manager.git[OK]
Installing... ... [FAIL]
unable to execute package manager: npm
 ERROR[0012] unable to execute package manager: npm command=install
 ERROR[0012] INSTALL ERROR: Unable to install selected package command=install
Unable to install selected package```

**Comment by pawelmisiak** [comment]
@tankchintan any luck with that issue?

**Comment by pawelmisiak** [comment]
if someone ever runs into this issue inspect your .npmrc file and make sure you have correct npmjs registry setup
