### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli-property-manager#18]
Here are the logs when i try installation manually.

_Originally posted by @vreddhi in https://github.com/akamai/cli-property-manager/issue_comments#issuecomment-435963760_

**Comment by vreddhi** [comment]
Attaching logs.

[2018-10-16T07_55_50_047Z-debug.log](https://github.com/akamai/cli-property-manager/files/2549875/2018-10-16T07_55_50_047Z-debug.log)

**Comment by jnchin-james** [comment]
How are you running your install command?  How do you run it with the debug command?

**Comment by vreddhi** [comment]
@jnchin-james I had to clone the repository manually under `~/.akamai-cli//src` and run `npm install`. @dshafik  helped me for the same.

**Comment by jnchin-james** [comment]
Strange!

I'm surprised @dshafik  wouldn't suggest installing it via "akamai install property-manager"

**Comment by vreddhi** [comment]
@jnchin-james Its a debug step, to figure out whats the issue. Can we focus on solving the issue in first place :)

**Comment by jnchin-james** [comment]
Hi Vreddhi, I would like to take this to a private email thread as I believe the general public does not have the same issue as you.

I will contact you over work email.

**Comment by vreddhi** [comment]
@jnchin-james Thank you for helping here.
