### ISSUE TITLE
Akamai pipeline - remove obligation to create at least two environments

### ISSUE THREAD

**Issue by gilevichalex** [akamai/cli-property-manager#20]
Hi, Team

thanks for a great work! Is it possible to remove the obligation to create at least two environments properties for akamai pipeline ? We have some devs that need only one environment (only prod). I don't wanna use different workflows for different teams, just wanna use pipeline for all.

Regards,
Alex

**Comment by jnchin-james** [comment]
Hi Alex

We have enabled you to create or work with a single property.  This is "akamai property-manager" command instead of the "akamai pipeline" command.  Check it out with

 akamai property-manager --help

**Comment by gilevichalex** [comment]
Hey, James

yeah, but those two tools have a different folder structure, also pipeline
has a native variables support which is cool. Anyway, thanks for reply

Regards,
Alex

ср, 14 нояб. 2018 г. в 16:20, jnchin-james <notifications@github.com>:
