### ISSUE TITLE
How does Etag being calculated ?

### ISSUE THREAD

**Issue by gilevichalex** [akamai/cli-property-manager#21]
Hello guys,

I'm thinking about some workaround for sync issues between SCM templates and real Akamai property state. Let's say we have some update via Luna config manager, I would like to find the diff, update templates and recalculate the etag. If I don't update the etag I'll get "The provided Etag is not the latest". So the question is which algorithm, filds etc. are used to calculate it ? Perhaps any other ideas/approaches to handle sync issues ?

Thanks.

**Comment by jnchin-james** [comment]
Hi

etag is computed from PAPI, and we are not able / willing to mention how etag is computed here.

Best I can say is that once you try and do a save when something is "out of sync" the error that comes back usually says something like "we were expecting etag X, but we have etag Y stored".  A quick solution  might be to update the etag in the envInfo file that you are changing to the expected etag.

Please use with caution.
