### ISSUE TITLE
Enhancement: add --edgerc parameter

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property-manager#23]
The CLI style guide https://developer.akamai.com/cli/docs/style-guide states all the Akamai CLIs should support 2 parameters: --edgerc and --section

Seems the first one is missing on this CLI. --edgerc which allows indicating the full path to the .edgerc file

**Comment by javiergarza** [comment]
I think the parameter should be in lowercase

**Comment by ynohat** [comment]
Concrete use case: in a Concourse CI job, the edgerc and the pipeline source files will be mounted into an isolated container in different directories, none of which will be the user's home dir.
IMHO, there is too much magic around `devopsHome`, aligning to the other CLIs and the style guide will also help users understand what behaviour to expect.

**Comment by lkowalsk-akamai-com** [comment]
Both flags are available. Closing.
