### ISSUE TITLE
variable.json - originhostnames

### ISSUE THREAD

**Issue by jazzista88** [akamai/cli-property-manager#26]
Hello all.
I tried to use akamai pipeline for the first time.
In details i need to use the akamai pipeline capability to separate all the parts of a rule in different snippets, add or delete something and rebuild the rule tree. 
i don't want to promote the change on akamai property because, if i understood well, if i specify STAGING, immediately the change will be activated on staging network, for now i would just see the change without activate it. Is it possible?

In the meanwhile i'm using akamai sandbox to update or create a sandbox property on which i can do some tests before going on staging or production. 
What i get is that the rebuilt rule tree replaces every origin hostname entry (inside a rule tree i have several different origins) with a variable, for instance:

origin-dev.AKAMAIPROPERTY

This prevent me to update my rule tree on the sandbox because the variable overwrite the real origin  name. 
Why the akamai pipeline does not download the rule tree with all the origin hostnames set?
Should i manually map all the origin hostnames manually? 

Thank you

**Comment by jnchin-james** [comment]
With Akamai Pipeline you can test your changes on different properties (such as a qa, staging, production) environments.  If you are trying to see the changes live somewhere, then I would suggest trying to push these to a lower level environment that is not customer facing, does that make sense?

**Comment by sidph** [comment]
@jazzista88 it might be worth using the CLI's merge command here - this generates an updated local rule true in your /dist folder without the need to activate. You can then use this with your sandbox

**Comment by jazzista88** [comment]
Actually i just discovered that for any environment defined a property is created, :P
The change i have done on dev has been done so this is what i wanted to know. I think that the creation of a property for each environment means a not clean configuration, so i need the sandbox to test the changes on it and then promote them on staging or prod.
Sorry @sidph i didn't get what merge command does.

**Comment by sidph** [comment]
Perfect - glad you are on your way! Merge simply stitches together all the snippets and variables into a JSON file on the client side, without the need to activate your property on the Akamai network

**Comment by jazzista88** [comment]
@sidph 
Since the presence of all these new akamai properties like dev.PROPERTY, qa.PROPERTY, prd.PROPERTY it's a bit confused i need to remove them. In particular i need to remove a pipeline, is there any command or i can simply delete the {env}.PROPERTY rules ?

**Comment by jazzista88** [comment]
However, the issue i have is still there. I mean, the origin name has been replaced by the variable origin-dev.PROPERTY.
I dont' understand why

**Comment by sidph** [comment]
Not via the CLI today but that's a good thought around a clean pipeline removal- we'll add it to our backlog. In the interim you can use the underlying API's delete command to individually get rid of the properties - https://developer.akamai.com/api/core_features/property_manager/v1.html#deleteproperty

**Comment by jazzista88** [comment]
Thank you @sidph 
From my understanding i see that when the akamai pipeline create all the separated snippets, the list of different origin defined in origin server behaviour are overwritten by the variable defined in variables.json>"originHostname": origin-{env}.PROPERTYNAME
Why this happens? 
I have multiple origin server behaviours with different origins name, in this way i should always edit it manually?

**Comment by synedra** [comment]
You can always use the Akamai property command, which doesn’t require a specific development process.

Kirsten

Sent from my iPhone

On Feb 6, 2019, at 8:40 AM, jazzista88 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you @sidph<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sidph&d=DwMFaQ&c=96ZbZZcaMF4w0F4jpN6LZg&r=Q1_WK8mWWUtQ5xZX1lcsIPCasN7Y3hsyzvEZltDs4Vs&m=QMnMRSIzmkmotiHxziR9aTkta4r7oIAxLDOBmC_CWdU&s=ACmq07lsnqCOTuHiCX4w864ZeJj-ox0q_KozxfxGxAU&e=>
From my understanding i see that when the akamai pipeline create all the separated snippets, the list of different origin defined in origin server behaviour are overwritten by the variable defined in variables.json>"originHostname": origin-{env}.PROPERTYNAME
Why this happens?
I have multiple origin server behaviours with different origins name, in this way i should always edit it manually?

**Comment by jnchin-james** [comment]
unfortunately jazzista, yes you would need to manually overwrite each section for each seperate origin behavior

**Comment by jazzista88** [comment]
@sidph Can i simply remove the properties created with akamai pipeline by luna interface?

**Comment by jazzista88** [comment]
@jnchin-james 
Thank you for your answer.
This means that generally in a property is supposed to have just one origin ?
Within our akamai properties, we commonly have the default origin and then, due to business reasons, there are several different origins on which there are different resources to collect under specific criteria for instance.
Due to these reasons, i expect that akamai pipeline when downloading the JSON rule tree maintains the name of all the origins within it so that the different snippets created continue having these origins set as in property manager.
Is it currently possible ?
I really thank you.

**Comment by jazzista88** [comment]
i'm continuing testing akamai pipeline, i understoos the way to declare an alternate origin and it seems to work. However for automation purposes it is not feasible edit manually each origin within a property.
Moreover, the command merge has been mentioned, i was wondering if there is the opposite, i mean an explicit command like akamai pipeline split, able to take the whole property manager rule tree and split it in the related snippets.
Thank you again for your support

**Comment by jnchin-james** [comment]
No, of course you are allowed to set up multiple origins depending on your needs.

You could always try with the new-pipeline command with the option "--variable-mode no-var" which would not create variables for you and it would try to leave as much as possible intact.

**Comment by jazzista88** [comment]
Thank you @jnchin-james 
With your suggestion i finally have the property snippets without any variable inside it, i want share with you the command used to do that.
When you are going to create a new pipeline:

akamai pipeline new-pipeline --variable-mode no-var -p {pipeline_name} -e {akamai_property} {env1} {env2}

I really thank you guys!
