### ISSUE TITLE
How to set permissions on different snippets

### ISSUE THREAD

**Issue by jazzista88** [akamai/cli-property-manager#27]
Hi all,

I'm trying to follow the federated development workflow.
I read this:
"Within this folder, the main.json file ties all the snippets together: It lists the available snippets and contains the local permissions for each snippet. You can modify both the list of snippets and their permissions."

I created a local property using an existing one as blue print.

I also read in the "Create snippets of your Property Manager configuration" section point 6 that i can set permissions on each JSON snippet:

"If required, set up local permissions for each JSON snippet."

I would understand how to do that.

Thank you in advance

**Comment by sidph** [comment]
@jazzista88 - permissions here imply local permissions you'd typically use with any other client side files. This isn't specifically built into the tool - but just enabled since you can set your own processes around this since all snippets is client side

**Comment by jazzista88** [comment]
Thank you @sidph maybe i don't have the knowledge you are talking about.
You mean set the appropriate permissions using shell command like chmod/chown?
Thanks

**Comment by sidph** [comment]
Yep!
