### ISSUE TITLE
activated version doesnt show

### ISSUE THREAD

**Issue by jamalsia** [akamai/cli-property-manager#28]
we are promoting version 1 of a property to akamai using the akamai pipeline
we noticed that when the command fails the status shown is wrong as compared to what is showing in Luna.
the only solution found is to delete the whole property and to recreate it entirely.
There should be a way to refresh the version currently activated in the akamai remote servers in order to resume failing jobs on a CI/CD pipeline. 
if the promotion commands fails to report the status. the commands
akamai pl cs -p myproperty -w prod

akamai pl lstat 
will show N/A. where  as in luna, we will see that version 1 is promoted.

as in
╒═════════════╤════════════╤══════════════════════╕
│"Environment"│"Network"   │"Active Version"      │
╞═════════════╪════════════╪══════════════════════╡
│"prod"       │"staging"   │"No version is active"│
├─────────────┼────────────┼──────────────────────┤
│"prod"       │"production"│"No version is active"│
└─────────────┴────────────┴──────────────────────┘

running akamai pipeline promote -p myproperty --network staging
returns
Akamai Pipeline Error: 'api_client_error' occurred:
 Request failed, status code: 403,
Response Body: '{
  "type" : "https://problems.luna.akamaiapis.net/papi/v0/property-version/already-activated",
  "title" : "Property version already activated",
  "detail" : "Version 1 of property `prp_1234567` has already been activated.  To make changes you must first create a new property version.",
  "instance" : "https://akab-pnzhyxxxxxxxxx-fxxxxxxxp.luna.akamaiapis.net/papi/v0/properties/1234567/versions/1/hostnames?contractId=xxxxxxxxx&groupId=xxxxxx#59add002-d076-46c4-8f68-5xxxxxxxxxxx",
  "status" : 403,
  "propertyId" : "prp_1234567",
  "propertyVersion" : 1
}'

**Comment by jamalsia** [comment]
the workaround is to change the template by adding an additional character in one of the template files. and to push again to akamai.

**Comment by jamalsia** [comment]
we are having additional issues 

we deployed a property in our test, preprod environments.
when deploying to the production environment, we have the following error

akamai pipeline promote -p xxx.api.xxxx.com prod --force --network staging --emails jx@x.com -w --message 'Created api'
Akamai Pipeline Error: 'api_client_error' occurred:
 Request failed, status code: 403,
Response Body: '{
  "type" : "https://problems.luna.akamaiapis.net/papi/v0/property-version/already-activated",
  "title" : "Property version already activated",
  "detail" : "Version 1 of property `prp_507918` has already been activated.  To make changes you must first create a new property version.",
  "instance" : "https://akab-pnzhy3pszkrcwpzs-f4nimtgrjsbglznp.luna.akamaiapis.net/papi/v0/properties/507918/versions/1/hostnames?contractId=3-XXXXX&groupId=XXXX#bba5e97e-146b-4523-b95b-4ddf38875955",
  "status" : 403,
  "propertyId" : "prp_507918",
  "propertyVersion" : 1


could you please tell us how to fix it?
 i suppose there must be a way to force the update in a new version or clear the cache so that the version doesnt point to version 1 anymore but is incremented automatically

**Comment by jnchin-james** [comment]
Hi jamalsia

It seems to me that the property version on property manager has been activated, and that it is now out of sync with what the cli knows.

You can try to update the envInfo file and change the activation status to "Active".  This will help give a hint to the cli that it will need to create a new version. You might also need to make a small change to the template to have the cli so that it thinks there is a change it needs to promote.

**Comment by jamalsia** [comment]
thank you jnchin-james
