### ISSUE TITLE
Enhancement: add JSON output format

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property-manager#30]
The output of the commands that list / show things use tables, which doesn't display properly in some terminals as the tables are pretty wide and wrap several times in smaller monitors. 

Another issue with tables is the output is not very good for automating processes. It will be great  to provide the output in JSON with a parameter like "--output json/table (default)"

It would be great to apply that to all outputs but if that's not possible, at least on the ones below:
- show-defaults
-   search
-   list-contracts
-   list-products
-   list-groups
-   list-cpcodes
-   list-edgehostnames
-   check-activation-status

**Comment by vreddhi** [comment]
--json is used in other CLI packages like firewall and CPS. So i would for the same, to be consistent across packages.

**Comment by jnchin-james** [comment]
Yes, actually you can do 

akamai pipeline set-default --format json

you can choose json or table
