### ISSUE TITLE
Unable to perform deployments on jenkins server

### ISSUE THREAD

**Issue by TraGicCode** [akamai/cli-property-manager#4]
It looks like when you perform an `akamai pd promote` a bunch of metadata in files called env.json get updated.  Future promotions and status checks then utilize this metadata to make decisions about what to do.   This causes a huge problem because of the way this metadata is used.  People who want to use a CI/CD server to promote their akamai changes ( instead of allowing developers to run promotions on their local box which is just bad practice ) will have this metadata updates in the currently directory in which the build is happening but it will be lost and cleaned up on the next run.  The next run then has no idea that is need to create a new version..etc.. and things blow up.

Is this being actively worked on or talked about?  Could we get some assistance?  This seems like a huge blocker.

@sidph @dshafik

**Comment by TraGicCode** [comment]
Yep i agree.  We also attempted to get our jenkins server to commit the metadata after the promote but it's not really ideal because now we.

1. Have to give jenkins non-readonly credentials
1. He will just clutter up git history with a bunch of "Commiting deployment state" commits
1. If we have triggers setup to deploy or perform changes on actions like when a commit comes in now we have to somehow prevent jenkins commit of metadata from triggering a build.

We also just had trouble getting jenkins to commit the metadata since he clone's the repo in a detached head state.  Also looking online it looks like noone even does commits from the ci/cd server.

**Comment by jnchin-james** [comment]
We are currently working towards an example of how you can use / set up jenkins.  You'll definitely be the first to be notified.

**Comment by TraGicCode** [comment]
Hey @jnchin-james ,

Thanks soo much.  I thought about doing this but long live branches are kind of a bad practice.  Though i think this is sufficient for now if the idea is that developers don't touch the long lived branches and the jenkins pipeline is the one to handle all the maintenance.

**Comment by TraGicCode** [comment]
Closing but thanks for the blog.  Will give it a read when i have time.
