### ISSUE TITLE
--section param should override setting in projectInfo.json

### ISSUE THREAD

**Issue by ynohat** [akamai/cli-property-manager#40]
I believe currently the edgerc section specified in projectInfo.json overrides the section provided on the command line.

This is problematic in "multiplayer" (CI or team) context because they might not all be using the same credential file as the one committed.

Workaround: remove the key from projectInfo.json and commit that to git.

**Comment by SidHeg** [comment]
This issue has been fixed. The section provided on the command line takes precedence over the section specified in projectInfo.json.
