### ISSUE TITLE
snippetsSettings.json: Removed

### ISSUE THREAD

**Issue by DidierFort** [akamai/cli-property-manager#47]
Hello,

That file is being removed from time to time, it seems to be correlated to the log rotation.

Regards,
Didier

**Comment by DidierFort** [comment]
Confirmed today, when I ran 'akamai snippets i -p ...' it created a new gzipped log and removed snippetsSettings.json.

**Comment by zstlaw** [comment]
Thank you for the bug report. We recently identified the cause of this issue and have a new release coming out in about a week.
