### ISSUE TITLE
Property version created when using `property-manager merge`

### ISSUE THREAD

**Issue by optplx** [akamai/cli-property-manager#48]
When using `property-manager merge -p ${PROPERTY} --format json`, i have sometime a new version of my property created at Akamai side. As per my understanding it should be a "local-only" command (specifically to generate locally the ruletree from the config snippets).

Please note that a new version is not always created, it looks like it is when the current version is active in production or staging.

thanks for your help

**Comment by mitaliich** [comment]
The property manager CLI creates new property version as it has to validate the rule tree on merge. It cannot validate if the version is active. Hence, it creates a new version.
There is an option to merge without validating. This is can be used to avoid creating new version.
