### ISSUE TITLE
Choose version to activate in production/staging

### ISSUE THREAD

**Issue by optplx** [akamai/cli-property-manager#49]
When using "akamai property-manager activate", we can't choose the version to activate. It would be great to be able to chose the version, we may not want to choose the latest everytime

**Comment by SidHeg** [comment]
A new command activate-version is added in the 0.7.0 version. This command lets you choose the version to activate.

**Comment by SidHeg** [comment]
An example of this command:
akamai property-manager activate-version -p test.example.com -n stag --propver 2 -m "activating version 2 in staging environment"
