### ISSUE TITLE
property manager version out of sync

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-property-manager#56]
I updated the property-manager to the latest version (0.7.1 as of writing), however if I search for it using "akamai search" the CLI tells me the latest version is 0.5.1 (see output below). This seems to be because the property-manager developer is not updating the information inside https://developer.akamai.com/cli/package-list.json.

As far as I know, akamai CLI developers need to file a pull request on https://github.com/akamai/cli/blob/master/assets/package-list.json to have the master manifest updated each time they push a new release of their CLI package (FYI @mvanhornakamai) 

```
$ akamai property-manager --version  
0.7.1-RELEASE
$ akamai search property-manager 
Results Found: 1

Package: Property Manager 2.0 [property-manager]
  Command: snippets (aliases: pm, property-manager)
  Version: **0.5.1**
  Description: Property Manager CLI for DevOps


Install using "akamai install [package]".
```

**Comment by SidHeg** [comment]
This issue has been resolved.
