### ISSUE TITLE
Add a confirmation message to the "set-default" command

### ISSUE THREAD

**Issue by akshayranganath** [akamai/cli-property-manager#6]
When the `--set-default` command is executed, it quietly exits. It will be good to have 2 things:

- Confirm the execution of the command
- Print the current defaults. So we may need a new option like `--show-default` for this.

**Comment by jnchin-james** [comment]
Thank you for the comment.

We currently have implemented the second half of this request

show-defaults|sf                                   Show default settings for this workspace

**Comment by jnchin-james** [comment]
Hello

We now have the first half implemented for the confirmation of the "set-default".  This will now show the results of setting the default in a table.
