### ISSUE TITLE
validation.unknown_condition_attribute.html

### ISSUE THREAD

**Issue by roymartinezblanco** [akamai/cli-property-manager#64]
When trying to merge a given configuration (using latest v2020–03–04), schema validation fails due to normalize tag in match criteria as seen below:
Step 1:
``` akamai property-manager import -p roymartinez.dev```

Step 2:
``` akamai property-manager merge -p roymartinez.dev```

```json
    {
        "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/unknown_attribute",
        "errorLocation": {
            "template": "config-snippets/xxxx.json",
            "variables": [],
            "location": "children/5/criteria/0/options/normalize",
            "value": false
        },
        "detail": "[validation.unknown_condition_attribute.html]"
    }
```

this does not allow commands, merge, activate, etc to work due to what seems to be an out of date schema validation

**Comment by lkowalsk-akamai-com** [comment]
Closing as there are new rule formats. Please revalidtate and create new issue if problem still occurs.
